"""Analyze complete implementation status across the repository.

This script parses intermediate data generated by 'jules-completist' scans
and produces structured reports and prioritized issue lists.

Principles:
- DRY: Consolidated redundant file scanning loops into a generic helper.
- Orthogonality: Separates data extraction from report generation logic.
"""

from __future__ import annotations

import glob
import logging
import os
import re
from collections.abc import Callable, Mapping
from datetime import datetime
from typing import Any, TypedDict, cast

# Constants and Configuration
DATA_DIR = ".jules/completist_data"
REPORT_DIR = "docs/assessments/completist"
ISSUES_DIR = "docs/assessments/issues"

FILES_MAP = {
    "MARKERS": os.path.join(DATA_DIR, "todo_markers.txt"),
    "NOT_IMPL": os.path.join(DATA_DIR, "not_implemented.txt"),
    "STUBS": os.path.join(DATA_DIR, "stub_functions.txt"),
    "DOCS": os.path.join(DATA_DIR, "incomplete_docs.txt"),
    "ABSTRACT": os.path.join(DATA_DIR, "abstract_methods.txt"),
}

EXCLUDED_PATHS = [
    "scripts/analyze_completist_data.py",
    "docs/",
    ".github/",
    ".jules/",
    "CRITICAL_PROJECT_REVIEW.md",
    "WORKFLOW_AND_AGENTS_REPORT.md",
    "pyproject.toml",
]


logger = logging.getLogger(__name__)


class _FindingOptional(TypedDict, total=False):
    text: str
    name: str


class Finding(_FindingOptional):
    file: str
    line: str
    type: str


def is_excluded(filepath: str) -> bool:
    """Check if filepath should be excluded from analysis."""
    if not isinstance(filepath, str):
        raise TypeError(f"filepath must be a str, got {type(filepath).__name__}")
    if not filepath:
        return True

    fp = filepath.replace("\\", "/")
    if fp.startswith("./"):
        fp = fp[2:]

    for excl in EXCLUDED_PATHS:
        if fp.startswith(excl) or excl in fp:
            return True
    return False


def _parse_grep_line(line: str) -> tuple[str | None, str | None, str | None]:
    """Parse a standard 'file:line:content' grep output line."""
    parts = line.split(":", 2)
    if len(parts) < 3:
        return None, None, None
    return parts[0], parts[1], parts[2].strip()


def _scan_completist_file(
    source_key: str, parser: Callable[[str], Finding | None]
) -> list[Finding]:
    """Generic helper to scan a completist data file and parse findings."""
    if not isinstance(source_key, str) or not source_key:
        raise ValueError(f"source_key must be a non-empty str, got {source_key!r}")
    if not callable(parser):
        raise TypeError(f"parser must be callable, got {type(parser).__name__}")
    source_path = FILES_MAP.get(source_key)
    if not source_path or not os.path.exists(source_path):
        return []

    results: list[Finding] = []
    with open(source_path, encoding="utf-8", errors="replace") as f:
        for line in f:
            finding = parser(line)
            if finding and not is_excluded(finding["file"]):
                results.append(finding)
    return results


def _parse_marker_line(line: str) -> Finding | None:
    """Parse a single grep line into a marker Finding (todo or fixme), or None."""
    # Obfuscate strings to avoid finding this script itself in greedy scans
    todo_str = "TO" + "DO"
    fixme_markers = ["FIX" + "ME", "XXX", "HACK", "TEMP"]

    filepath, lineno, content = _parse_grep_line(line)
    if not filepath or not lineno or content is None:
        return None

    if re.search(r"\b" + todo_str + r"\b", content):
        return Finding(file=filepath, line=lineno, text=content, type="TO" + "DO")

    for m_marker in fixme_markers:
        if re.search(r"\b" + m_marker + r"\b", content):
            return Finding(file=filepath, line=lineno, text=content, type=m_marker)

    return None


def analyze_todos() -> tuple[list[Finding], list[Finding]]:
    """Analyze TO-DO and FIX-ME markers."""
    todos: list[Finding] = []
    fixmes: list[Finding] = []

    all_markers = _scan_completist_file("MARKERS", _parse_marker_line)
    for marker_item in all_markers:
        if marker_item["type"] == "TO" + "DO":
            todos.append(marker_item)
        else:
            fixmes.append(marker_item)

    return todos, fixmes


def analyze_stubs() -> list[Finding]:
    """Analyze stub functions."""

    def _parser(line: str) -> Finding | None:
        parts = line.strip().rsplit(" ", 1)
        if len(parts) < 2 or ":" not in parts[0]:
            return None
        filepath, lineno = parts[0].rsplit(":", 1)
        return Finding(file=filepath, line=lineno, name=parts[1], type="Stub")

    return _scan_completist_file("STUBS", _parser)


def analyze_docs() -> list[Finding]:
    """Analyze missing documentation."""

    def _parser(line: str) -> Finding | None:
        parts = line.strip().rsplit(" ", 1)
        if len(parts) < 2 or ":" not in parts[0]:
            return None
        filepath, lineno = parts[0].rsplit(":", 1)
        return Finding(file=filepath, line=lineno, name=parts[1], type="DocGap")

    return _scan_completist_file("DOCS", _parser)


def analyze_not_implemented() -> list[Finding]:
    """Analyze Not Implemented Error occurrences."""
    ni_str = "NotImplemented" + "Error"

    def _parser(line: str) -> Finding | None:
        f_path, l_no, c_txt = _parse_grep_line(line)
        if f_path and l_no and c_txt and ni_str in c_txt:
            return Finding(file=f_path, line=l_no, text=c_txt, type=ni_str)
        return None

    return _scan_completist_file("NOT_IMPL", _parser)


def analyze_abstract_methods() -> list[Finding]:
    """Analyze Abstract Methods."""

    def _parser(line: str) -> Finding | None:
        f_path, l_no, c_txt = _parse_grep_line(line)
        if f_path and l_no and c_txt and "@abstractmethod" in c_txt:
            return Finding(file=f_path, line=l_no, text=c_txt, type="Abstract")
        return None

    return _scan_completist_file("ABSTRACT", _parser)


def calculate_metrics(item: Mapping[str, Any]) -> tuple[int, int, int]:
    """Calculate heuristics for Impact, Coverage, and Complexity (1-5 range)."""
    if not isinstance(item, Mapping):
        raise TypeError(f"item must be a Mapping, got {type(item).__name__}")
    if "file" not in item:
        raise ValueError("item must contain a 'file' key")
    filepath = cast(str, item["file"])
    itype = cast(str, item.get("type", ""))

    impact = (
        5
        if any(x in filepath for x in ["shared/python", "engines/", "api/"])
        else (3 if "tools/" in filepath else 1)
    )
    coverage = 5 if "tests/" in filepath else (3 if "shared/python" in filepath else 2)

    # Complexity mapping
    comp_map = {
        "Stub": 4,
        "NotImplementedError": 4,
        "FIX" + "ME": 2,
        "TO" + "DO": 3,
        "DocGap": 1,
        "Abstract": 5,
    }
    complexity = comp_map.get(itype, 3)

    return impact, coverage, complexity


def _build_issue_content(
    item: Mapping[str, Any],
    itype: str,
    f_path: str,
    l_no: str,
    context: str,
    title: str,
) -> str:
    """Return the markdown content for a new issue file."""
    impact, coverage, complexity = calculate_metrics(item)
    labels: list[str] = ["incomplete-implementation", "critical"]
    if impact >= 5:
        labels.append("high-impact")
    return (
        f'---\ntitle: "{title}"\nlabels: {labels}\nassignee: "unassigned"\n'
        f'status: "open"\n---\n\n# Issue Description\n'
        f"Found critical incomplete implementation in `{f_path}` at line {l_no}.\n\n"
        f"## Context\n**Type**: {itype} | **Location**: `{f_path}:{l_no}`\n\n"
        f"```python\n{context}\n```\n\n"
        f"## Audit Metrics\n"
        f"- **Impact**: {impact}/5 | **Coverage**: {coverage}/5"
        f" | **Complexity**: {complexity}/5\n\n"
        f"## Recommendation\n"
        f"Implement missing logic or document the rationale for the gap.\n"
    )


def create_issue_file(item: Mapping[str, Any], issue_id: int) -> str:
    """Idempotent creation of markdown issue files."""
    if not isinstance(item, Mapping):
        raise TypeError(f"item must be a Mapping, got {type(item).__name__}")
    if not isinstance(issue_id, int) or issue_id <= 0:
        raise ValueError(f"issue_id must be a positive int, got {issue_id!r}")
    os.makedirs(ISSUES_DIR, exist_ok=True)

    itype = str(item.get("type", "Incomplete Implementation"))
    f_path, l_no = str(item["file"]), str(item["line"])
    context = str(item.get("name", item.get("text", "")))
    title = f"Incomplete {itype} in {os.path.basename(f_path)}:{l_no}"
    fname_title = re.sub(r"[^\w]", "_", title).strip("_")

    existing = glob.glob(os.path.join(ISSUES_DIR, f"Issue_*_{fname_title}.md"))
    if existing:
        return existing[0]

    filepath = os.path.join(ISSUES_DIR, f"Issue_{issue_id:03d}_{fname_title}.md")
    content = _build_issue_content(item, itype, f_path, l_no, context, title)
    with open(filepath, "w", encoding="utf-8") as f:
        f.write(content)
    return filepath


def _validate_chart_inputs(
    criticals: list[Finding],
    todos: list[Finding],
    fixmes: list[Finding],
    docs: list[Finding],
) -> None:
    """Raise TypeError if any chart input is not a list."""
    for name, value in (
        ("criticals", criticals),
        ("todos", todos),
        ("fixmes", fixmes),
        ("docs", docs),
    ):
        if not isinstance(value, list):
            raise TypeError(f"{name} must be a list, got {type(value).__name__}")


def _build_status_overview_chart(
    criticals: list[Finding],
    todos: list[Finding],
    fixmes: list[Finding],
    docs: list[Finding],
) -> list[str]:
    """Return mermaid pie chart lines for the overall status overview."""
    todo_label = "TO" + "DO"
    fixme_label = "FIX" + "ME"
    return [
        "### Status Overview",
        "```mermaid",
        "pie title Completion Status",
        f'    "Impl Gaps (Critical)" : {len(criticals)}',
        f'    "Feature Requests ({todo_label})" : {len(todos)}',
        f'    "Technical Debt ({fixme_label})" : {len(fixmes)}',
        f'    "Doc Gaps" : {len(docs)}',
        "```",
    ]


def _build_module_breakdown_chart(
    criticals: list[Finding],
    todos: list[Finding],
    fixmes: list[Finding],
) -> list[str]:
    """Return mermaid pie chart lines for the top impacted modules."""
    counts: dict[str, int] = {}
    for item in criticals + todos + fixmes:
        path_parts = item["file"].split("/")
        root = path_parts[0] if path_parts else "unknown"
        if root in [".", "src"]:
            root = path_parts[1] if len(path_parts) > 1 else root
        counts[root] = counts.get(root, 0) + 1

    sorted_mods = sorted(counts.items(), key=lambda x: x[1], reverse=True)[:5]
    if not sorted_mods:
        return []
    lines = ["\n### Top Impacted Modules", "```mermaid", "pie title Issues by Module"]
    lines.extend(f'    "{mod}" : {count}' for mod, count in sorted_mods)
    lines.append("```")
    return lines


def generate_mermaid_charts(
    criticals: list[Finding],
    todos: list[Finding],
    fixmes: list[Finding],
    docs: list[Finding],
) -> str:
    """Generate Mermaid charts for the report."""
    _validate_chart_inputs(criticals, todos, fixmes, docs)
    chart: list[str] = ["## Visualization"]
    chart.extend(_build_status_overview_chart(criticals, todos, fixmes, docs))
    chart.extend(_build_module_breakdown_chart(criticals, todos, fixmes))
    return "\n".join(chart)


class _ReportData(TypedDict):
    """Bundle of scanned findings used to render a completist report."""

    criticals: list[Finding]
    todos: list[Finding]
    fixmes: list[Finding]
    missing_docs: list[Finding]


def _collect_report_data() -> _ReportData:
    """Scan completist sources and return prioritized finding lists."""
    stubs = analyze_stubs()
    ni_errors = analyze_not_implemented()
    todos, fixmes = analyze_todos()
    missing_docs = analyze_docs()
    _ = analyze_abstract_methods()

    # Identify and prioritize critical candidates
    criticals = [s for s in (stubs + ni_errors) if "test" not in s["file"].lower()]
    criticals.sort(key=lambda x: calculate_metrics(x)[0], reverse=True)

    return _ReportData(
        criticals=criticals,
        todos=todos,
        fixmes=fixmes,
        missing_docs=missing_docs,
    )


def _build_critical_table(criticals: list[Finding]) -> list[str]:
    """Return the markdown table rows for the critical incomplete items."""
    lines = [
        "\n## Critical Incomplete (Top 50)",
        "| File | Line | Type | Impact | Coverage | Complexity |",
        "|---|---|---|---|---|---|",
    ]
    for item in criticals[:50]:
        imp, cov, comp = calculate_metrics(item)
        lines.append(
            f"| `{item['file']}` | {item['line']} | {item['type']} | "
            f"{imp} | {cov} | {comp} |"
        )
    return lines


def _build_feature_and_debt_tables(
    todos: list[Finding], fixmes: list[Finding]
) -> list[str]:
    """Return markdown table rows for feature gaps and technical debt."""
    lines = [
        "\n## Feature Gap Matrix",
        "| Module | Feature Gap | Type |",
        "|---|---|---|",
    ]
    for item in todos[:50]:
        text = item.get("text", "").replace("|", "\\|")
        lines.append(f"| `{item['file']}` | {text[:100]} | {item['type']} |")

    lines += [
        "\n## Technical Debt Register",
        "| File | Line | Issue | Type |",
        "|---|---|---|---|",
    ]
    for item in fixmes:
        text = item.get("text", "").replace("|", "\\|")
        lines.append(
            f"| `{item['file']}` | {item['line']} | {text[:100]} | {item['type']} |"
        )
    return lines


def _build_implementation_order(
    criticals: list[Finding], todos: list[Finding]
) -> list[str]:
    """Return the markdown table rows for recommended implementation order."""
    lines = [
        "\n## Recommended Implementation Order",
        "Prioritized by Impact (High) and Complexity (Low).",
        "| Priority | File | Issue | Metrics (I/C/C) |",
        "|---|---|---|---|",
    ]
    all_items = sorted(
        criticals + todos,
        key=lambda it: (calculate_metrics(it)[0] * 10) - calculate_metrics(it)[2],
        reverse=True,
    )
    for i, item in enumerate(all_items[:20], 1):
        imp, cov, comp = calculate_metrics(item)
        desc = item.get("name", item.get("text", ""))[:80].replace("|", "\\|")
        lines.append(f"| {i} | `{item['file']}` | {desc} | {imp}/{cov}/{comp} |")
    return lines


def _build_report_body(data: _ReportData, date_s: str) -> list[str]:
    """Build the full markdown report body from collected data."""
    criticals = data["criticals"]
    todos = data["todos"]
    fixmes = data["fixmes"]
    missing_docs = data["missing_docs"]

    report: list[str] = [
        f"# Completist Report: {date_s}\n",
        "## Executive Summary",
        f"- **Critical Gaps**: {len(criticals)}",
        f"- **Feature Gaps (TO{'DO'})**: {len(todos)}",
        f"- **Technical Debt**: {len(fixmes)}",
        f"- **Documentation Gaps**: {len(missing_docs)}\n",
        generate_mermaid_charts(criticals, todos, fixmes, missing_docs),
    ]
    report.extend(_build_critical_table(criticals))
    report.extend(_build_feature_and_debt_tables(todos, fixmes))
    report.extend(_build_implementation_order(criticals, todos))
    return report


def _create_issues_section(criticals: list[Finding]) -> list[str]:
    """Create issue files for high-impact criticals and return a report section."""
    lines = ["\n## Issues Created"]
    max_id = 0
    issues_glob = glob.glob(os.path.join(ISSUES_DIR, "Issue_*.md")) + glob.glob(
        os.path.join(ISSUES_DIR, "ISSUE_*.md")
    )
    for issue_p in issues_glob:
        match_id = re.search(r"(\d+)", os.path.basename(issue_p))
        if match_id:
            max_id = max(max_id, int(match_id.group(1)))

    next_id = max_id + 1
    for item in [c for c in criticals if calculate_metrics(c)[0] >= 4][:10]:
        lines.append(f"- Created `{create_issue_file(item, next_id)}`")
        next_id += 1
    return lines


def _write_report_files(report_lines: list[str], date_s: str) -> str:
    """Write the report to its dated and 'latest' paths; return dated path."""
    os.makedirs(REPORT_DIR, exist_ok=True)
    report_path = os.path.join(REPORT_DIR, f"Completist_Report_{date_s}.md")
    payload = "\n".join(report_lines)
    with open(report_path, "w", encoding="utf-8") as f_out:
        f_out.write(payload)

    latest_path = os.path.join(REPORT_DIR, "COMPLETIST_LATEST.md")
    with open(latest_path, "w", encoding="utf-8") as f_out:
        f_out.write(payload)

    return report_path


def generate_report() -> None:
    """Generate the structured completist status report.

    Thin orchestrator: collects data, builds the report body, creates
    issue files for high-impact items, and writes the resulting markdown
    to disk.
    """
    data = _collect_report_data()
    date_s = datetime.now().strftime("%Y-%m-%d")

    report_lines = _build_report_body(data, date_s)
    report_lines.extend(_create_issues_section(data["criticals"]))

    report_path = _write_report_files(report_lines, date_s)
    logger.info("Report generated: %s", report_path)


if __name__ == "__main__":
    logging.basicConfig(level=logging.INFO)
    generate_report()
